### ISSUE TITLE
Branch ShaderGen no longer needed.

### ISSUE THREAD

**Issue by rn7s2** [rscrsc/eltitnu#2]
Reason:
- It is no longer a C++ project.
- .NET build command `dotnet build` will automatically copy `Shaders/**` to build folder, so no hard-coding is needed now.

**Comment by rscrsc** [comment]
But after copied, we still need a "Shader" class to load it into OpenGL and then the GPU

**Comment by rn7s2** [comment]
See `src/Common/Shader.cs`. It wraps more functions than older Shader class.

**Comment by rscrsc** [comment]
In our new structure, functions to load shaders and process shader should be separated.
