### ISSUE TITLE
Wrong binding

### ISSUE THREAD

**Issue by rscrsc** [rscrsc/eltitnu#5]
In this test world, the upper three should be dirt blocks, and the lower ones should be creepers, but now they use the same buffers.
I suspect it is because we didn't unbind, but I'm not sure what to do.

**Comment by rn7s2** [comment]
The reason is in class ObjectRender, VAO remains the last prepared value.

In order, that is – dirt

**Comment by rn7s2** [comment]
No unbinding does no harm to anything.

It is binding that matters.

STATE MACHINE – OpenGL huh?



So I think we could:

  1.  Maintain a K-V pair in ObjectRender – bad, object hard to hash
  2.  Store VAO handle in GameObject – bad, hard to reuse GameObject
  3.  Maintain a list of (VAO: handle, isHidden: boolean) pair in GameObject

What do you think?

**Comment by rscrsc** [comment]
You're right
I want to learn further before fix it so that I can find the proper way

**Comment by rscrsc** [comment]
My intention was seperating the render details like VAO from GameObject, all packed in the Renderer class
Can we do it in that way?

**Comment by rn7s2** [comment]
I think you mean you want to make gameobject reusable.
That's plan 1 above.
Like I mentioned, hashing gameobject could be a problem (also performance suffers)

发自 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rscrsc** [comment]
You can tell me more details about the problem and suffer
Right now my TexturedModel and List<GameObject> are hashed together by a dictionary right?

**Comment by rscrsc** [comment]
Done by redesign

**Comment by rscrsc** [comment]
If you have better solution, reply here; or you can close this issue

**Comment by rn7s2** [comment]
so the problem solved
hashing and finding objects is time consuming especially there are lots of game objects (that's common for mc)
and i think a plain list of pair would be ok

**Comment by rscrsc** [comment]
You’re right
I’ll change later
