### ISSUE TITLE
In-game coordinate system

### ISSUE THREAD

**Issue by rscrsc** [rscrsc/eltitnu#7]
How to set our user coord system to express positions to users? OpenGL coord system is kind of weird.
I prefer a unique axis name like A-B-C, what do you think?
坐标的整点定在哪里？顶点，体心，还是面心？

**Comment by rn7s2** [comment]
我们统一用这个系建模，随后变换成OpenGL的，再改改正负号
      Y
      |
      |
     / ````````Z
   /
X

在这个系里，如果Steve正对我们，那么他的右脚脚后跟外侧就是原点
我们建模的时候都统一在第一卦限

你看如何

**Comment by rscrsc** [comment]
为啥用左手系😂
我是觉得如果变换的话，再用xyz，写的时候容易自己跟OpenGL混掉，所以变个名字
而且Minecraft是竖着是z我记得

**Comment by rn7s2** [comment]
唉，我试了下，还是右手系习惯不会出错
```
     Z
     |
     |
    / ````````Y
  /
X
```
那 OK，就是左右手叉积有个符号问题

我们还是习惯右手定则

**Comment by rn7s2** [comment]
BTW, 中英文混打似乎中间加空格更好看些
测试 Test 测试
测试Test测试
